language: c

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - curl -OL http://hgdownload.cse.ucsc.edu/admin/exe/linux.x86_64/bigWigToBedGraph
  - curl -OL http://hgdownload.cse.ucsc.edu/admin/exe/linux.x86_64/bedToBigBed
  - chmod 755 *
  - export PATH=$(pwd):$PATH
  - travis-tool.sh bootstrap
  - sudo apt-get install -y bedtools r-cran-ggplot2 r-cran-data.table libdb5.1++-dev libdb5.1-stl-dev
  - travis-tool.sh install_github tdhock/coseg@bigwig tdhock/cosegData tdhock/PeakSegJoint@new-pipeline tdhock/namedCapture
  
install:
  - make
  - chmod 755 PeakSegFPOP

script:
  - R --vanilla < test_run.R

notifications:
  email:
    on_success: change
    on_failure: change

